#!/bin/bash
# Remod by _Dreyannz_
# ==================================================

# Initializing Var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;

if [[ -e /etc/debian_version ]]; then
	#OS=debian
	RCLOCAL='/etc/rc.local'
else
	echo "You are not running this script on Debian OS"
	exit
fi

vps="vps";

if [[ $vps = "vps" ]]; then
	source="https://raw.githubusercontent.com/Clrkz/VPSAutoScrptz/master"
else
	source="https://raw.githubusercontent.com/Clrkz/VPSAutoScrptz/master"
fi

# go to root
cd

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# update
apt-get -y update

clear
echo ""
echo "I need to ask some questions before starting setup"
echo "You can leave the default option and just hit enter if you agree with the option"
echo ""
echo "First I need to know the new password of MySQL root user:"
read -p "Root Password   : " -e -i clrkz DatabasePass
echo ""
echo "Finally, name the Database Name for OCS Panels"
echo " Please, use one word only, no special characters other than Underscore (_)"
read -p "Database Name   : " -e -i OCS_PANEL DatabaseName
echo ""
echo "Okay, that's all I need. We are ready to setup your OCS Panels now"
read -n1 -r -p "Press any key to continue..."



echo "clear" >> .bashrc
echo 'echo -e "\e[94m:::::::::  :::::::::: :::::::::  :::::::::::"' >> .bashrc
echo 'echo -e "\e[94m:+:    :+: :+:        :+:    :+: :+:     :+:"' >> .bashrc
echo 'echo -e "\e[94m+:+    +:+ +:+        +:+    +:+        +:+ "' >> .bashrc
echo 'echo -e "\e[94m+#+    +:+ +#++:++#   +#++:++#+        +#+  "' >> .bashrc
echo 'echo -e "\e[94m+#+    +#+ +#+        +#+    +#+      +#+   "' >> .bashrc
echo 'echo -e "\e[94m#+#    #+# #+#        #+#    #+#     #+#    "' >> .bashrc
echo 'echo -e "\e[94m#########  ########## #########      ###    "' >> .bashrc
